import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class SQLBirthCerificate {
	int uid;
	String usname;
	String firstn;
	String lastn;
	String bidate;
	String gender;
	String biplace;
	String faname;
	String moname;
	String address;
	String state;
	String district;
	String taluk;
	String category;
	public SQLBirthCerificate(int uid1,String uname1,String fn,String ln,String bdate,String g,String bplace,String fname,String mname,String addr,String state1,String dis,String tal,String cats) throws ClassNotFoundException,SQLException{
		uid=uid1;
		usname=uname1;
		firstn=fn;
		lastn=ln;
		bidate=bdate;
		gender=g;
		biplace=bplace;
		faname=fname;
		moname=mname;
		address=addr;
		state=state1;
		district=dis;
		taluk=tal;
		category=cats;
		String url="jdbc:mysql://localhost:3306/panchayat";
		String uname="root";
		String pass="abhishek";
		String query="insert into Birth values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
		Class.forName("com.mysql.cj.jdbc.Driver");
		Connection con=DriverManager.getConnection(url,uname,pass);
		PreparedStatement st=con.prepareStatement(query);
		st.setInt(1, uid);
		st.setString(2,usname);
		st.setString(3,firstn);
		st.setString(4,lastn);
		st.setString(5,bidate);
		st.setString(6,gender);
		st.setString(7,biplace);
		st.setString(8,faname);
		st.setString(9,moname);
		st.setString(10,address);
		st.setString(11,state);
		st.setString(12,district);
		st.setString(13,taluk);
		st.setString(14,category);
		int count=st.executeUpdate();
		System.out.println(count+" row/s affected");
		st.close();
		con.close();
	}
}